version: "2"
services:
  todo:
    build:
      context: ./todo
      dockerfile: Dockerfile
    restart: always
    volumes:
    - .:/go/src/github.com/pmtabe1/go.microservices.api/demomicro_api/
    container_name: todo
    ports:
    - 8800:8081
  mongodb:
    command: mongod --smallfiles --logpath=/dev/null
    container_name: mongodb
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    image: mongo:latest
    ports:
    - 27017:27017