version: "3"
services:
  todo:
    build:
      context: ./todo
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/go/src/github.com/pmtabe1/go.microservices.api/demomicro_api/todo
    container_name: todoapi
    ports:
      - 8801:8081
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    # mongodb:
    #   command: mongod --smallfiles --logpath=/dev/null
    #   container_name: mongodbmicroapi
    #   environment:
    #   - MONGO_DATA_DIR=/data/db
    #   - MONGO_LOG_DIR=/dev/null
    #   image: mongo:latest
    #   ports:
    #   - 27017:27017
